#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: pyproject
#
Name     : pypi-picobox
Version  : 3.0.0
Release  : 3
URL      : https://files.pythonhosted.org/packages/29/58/62da7083e7d3ce07fb5d13c89636fe8d224083d1d724327636482167dfb9/picobox-3.0.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/29/58/62da7083e7d3ce07fb5d13c89636fe8d224083d1d724327636482167dfb9/picobox-3.0.0.tar.gz
Summary  : Dependency injection framework designed with Python in mind.
Group    : Development/Tools
License  : MIT
Requires: pypi-picobox-license = %{version}-%{release}
Requires: pypi-picobox-python = %{version}-%{release}
Requires: pypi-picobox-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(hatchling)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
Picobox
=======
.. image:: https://img.shields.io/pypi/v/picobox.svg
:target: https://pypi.python.org/pypi/picobox

%package license
Summary: license components for the pypi-picobox package.
Group: Default

%description license
license components for the pypi-picobox package.


%package python
Summary: python components for the pypi-picobox package.
Group: Default
Requires: pypi-picobox-python3 = %{version}-%{release}

%description python
python components for the pypi-picobox package.


%package python3
Summary: python3 components for the pypi-picobox package.
Group: Default
Requires: python3-core
Provides: pypi(picobox)

%description python3
python3 components for the pypi-picobox package.


%prep
%setup -q -n picobox-3.0.0
cd %{_builddir}/picobox-3.0.0
pushd ..
cp -a picobox-3.0.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1680552180
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -m build --wheel --skip-dependency-check --no-isolation

popd

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-picobox
cp %{_builddir}/picobox-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/pypi-picobox/da842d4700fe014ef91e543abdc9591439c15b06 || :
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
pip install --root=%{buildroot}-v3 --no-deps --ignore-installed dist/*.whl
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-picobox/da842d4700fe014ef91e543abdc9591439c15b06

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
